### ISSUE TITLE
constant stuttering in rainmeter animations

### ISSUE THREAD

**Issue by Sykeman2020** [rainmeter/rainmeter#343] opened 2023-04-17 13:37 UTC
Any time I have an animation on the rainmeter desktop display, such as an audio visualizer, miniplayer, or even just a spinning icon, there is a noticeable stutter every 3/4 second or so. I tried emptying the recycle bin (Reddit suggestion) and editing update times, and can't seem to find a solution anywhere.

**Comment by brianferguson** [comment] 2023-06-23 18:41
Closing this topic since the issue is most likely a skin issue, not a Rainmeter application issue.

Please continue the discussion on the Rainmeter forums.

-Brian

**Closed by brianferguson** 2023-06-23 18:41 UTC
