### ISSUE TITLE
High DPI screen

### ISSUE THREAD

**Issue by Muini** [rainmeter/rainmeter#60] opened 2016-01-15 10:21 UTC
Hi,

Is there a plan (or an existing way) to make rainmeter pixel perfect on High DPI Screen ? For the moment it's blurry :/

Thanks !

**Comment by geterns** [comment] 2016-01-22 11:50
It looks just fine in my surface pro 3...

**Comment by LoicVerrall** [comment] 2016-06-08 13:51
@Muini I have the same issue - even text appears blurry.

**Comment by 3V3RY1** [comment] 2016-06-08 13:55
My resolution is **3200x1800** and I have **262ppi**.
Everything appears blurry and it is very noticeable on such a high res screen.
I hope this can get sorted out!

Many thanks,
Luke

**Comment by charlesmilette** [comment] 2016-06-08 13:56
Try the method 1 suggested [here](http://www.askvg.com/fix-bold-blurry-or-hard-to-read-font-problem-in-windows-8-1/)

**Comment by 3V3RY1** [comment] 2016-06-08 13:58
Wow! That worked!

Thanks so much!

**Comment by charlesmilette** [comment] 2016-06-08 13:58
You're welcome

**Comment by ACinnamonUserInUK** [comment] 2017-01-02 21:24
I have a related (small) problem. It's this:

![untitled2](https://cloud.githubusercontent.com/assets/9998846/21596323/abfa34bc-d131-11e6-832c-e21e397ac979.png)

i.e. the text here (but only here, I think) isn't quite right - but, rather, squashed. Changing the DPI settings for Rainmeter didn't help. I think that changing my global DPI setting to 100 - its 120 at present - might fix the problem, but I set the DPI for a reason. Then again, the cause of the problem could be a custom size on my machine for various UI elements (e.g. message boxes). Anyhow, it would be nice were Rainmeter to be able to cope with such settings.

Windows 8.1 x64, on a 1920x1200 screen. Rainmeter 4.0.

**Comment by david-maus** [comment] 2017-05-10 23:23
Same problem here...

My Display is 28" with 4096x2160px.... its completly blurry.

The windows scaling is of course on 150%...i cant change this to 100% (everything is too small and not readable on os and program level on 100%).

If i disable dpi-scaling on rainmeter it is working but i have change every skin/widget manually. 

This solution is working halfway:
http://borcki.deviantart.com/art/Rainmeter-Simple-HiDPI-Aware-17-05-573983178

Widgets / skins must be edited but it is working, theoretical. :D (The scalingfactor is not correct, the right "displayedge" is in the middle of my screen) but this is another thing....


Is there a correct and working hidpi solution on the list?

**Comment by ACinnamonUserInUK** [comment] 2017-05-10 23:58
It seems that it would be good were someone assigned to this problem.

**Comment by SamusAranX** [comment] 2018-06-04 21:56
As high-DPI screens continue to catch on (especially in laptops), blurry skins get less and less appealing.

A future-proof way of implementing high-DPI support would be to sort of do what web browsers do: Units in skins are now device-independent points instead of pixels, and newer skins can opt-in to get the high-DPI treatment (with a HighDpi=1 switch in the skin's [Rainmeter] section maybe?).

**Comment by brianferguson** [comment] 2018-06-04 22:02
We are in the process of completely re-writing our rendering to use D2D, which has better capabilities for high-DPI monitors. Once complete, we will be looking for a solution to this.

I am going to close this issue since this has been on our radar for quite some time and doesn't really need any discussion.

-Brian

**Closed by brianferguson** 2018-06-04 22:02 UTC

**Comment by amadis33** [comment] 2019-07-20 21:27
The best way is go to C:\Program Files\Rainmeter and then right click in rainmeter.exe  /properties/compatibility/change setting ppp and mark this two properties


![Annotation 2019-07-20 162521](https://user-images.githubusercontent.com/32826261/61584309-0f3a9c00-ab0b-11e9-9fe1-169b01722f8c.png)
